This short "" -> c enables scanning instruments that include a 0d monitor... (Which seems to have been broken ~ forever...)
The functions involved in the detector output are not very readable to say the least ;-)

 - c is the comp name and will become the filename in the detector_import'ed DETECTOR struct,
corresponding  what is used elsewhere.

(mc/xrun silently assumes that any begin detector: block includes a filename - and would fail
fatally, see e.g. McStas 3.4:
 mcrun -c ILL_H22.instr -N2 m=2,3

Traceback (most recent call last):
  File "/Applications/McStas-3.4.app/Contents/Resources/mcstas/3.4/tools/Python/mcrun/mcrun.py", line 562, in <module>
    main()
  File "/Applications/McStas-3.4.app/Contents/Resources/mcstas/3.4/tools/Python/mcrun/mcrun.py", line 531, in main
    scanner.run()  # in optimisation.py
    ^^^^^^^^^^^^^
  File "/Applications/McStas-3.4.app/Contents/Resources/mcstas/3.4/tools/Python/mcrun/optimisation.py", line 261, in run
    detectors = mcsimdetectors(current_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/McStas-3.4.app/Contents/Resources/mcstas/3.4/tools/Python/mcrun/optimisation.py", line 171, in mcsimdetectors
    return [Detector(d['component'], *d['values'].split(), d['filename']) for d in blocks]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/McStas-3.4.app/Contents/Resources/mcstas/3.4/tools/Python/mcrun/optimisation.py", line 171, in <listcomp>
    return [Detector(d['component'], *d['values'].split(), d['filename']) for d in blocks]
                                                           ~^^^^^^^^^^^^
KeyError: 'filename'
)