Several fixes in relation to recent SANS contrib:
* Comps have to go in contrib/ without an extra folder - we could consider the other structure for the future...
* Instrumentfile needs an %INSTRUMENT_SITE: token, otherwise mcgui gives us trouble (patch the tool also?)
* Parameter naming for Source_simple instance in the instrumentfile was 1.12c style, updated names
* Consider per-component test file

Furhter work still needed since at least SANSLiposomes has issues:

Instrument file: TestSANS.instr
Translating instrument definition 'TestSANS.instr' into C ...
mcstas-2012-Nov-05 -t -o TestSANS.c TestSANS.instr
Compiling simulation TestSANS.instr
Info:    'SANSLiposomes' is a contributed component.
syntax error, unexpected TOK_ID, expecting END at line 66.


Fatal error: Errors encountered during autoload of component SANSLiposomes.


Program aborted.
Job exited abnormally.