Workaround for combined mcgui/mcrun/mcdisplay*py* issue:
When a changed instrument file causes recompile via the mcrun --info call, the full path causes a full path to appear in the INSTRUMENT line for later parsing...

This makes *py mcdisplay break down with

WARNING: t_ignore contains a literal backslash '\'
Syntax error in input!
LexToken(COMPONENT,'COMPONENT',2,12)
InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"
Traceback (most recent call last):
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 566, in <module>
    raise e
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 561, in <module>
    main(args)
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/mcdisplay.py", line 533, in main
    instrument = reader.read_instrument()
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/mcdisplayutils.py", line 69, in read_instrument
    instrbuilder = InstrObjectConstructor(instrparser.parsetree)
  File "/Applications/McStas-2.4pre01.app/Contents/Resources/mcstas/2.4pre01/bin/../tools/Python/mcdisplay/pyqtgraph/../../mccodelib/instrparser.py", line 266, in __init__
    raise Exception('InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"')
Exception: InstrObjectConstructor: parsetreeroot must be a Node of type "instrdeftree"